[project]
name = "manuspress-agent-agency"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "crewai>=1.7.2",
    "crewai-tools>=1.7.2",
    "openai>=1.83.0",
    "python-dotenv>=1.1.1",
    "pyyaml>=6.0.3",
]
